### ISSUE TITLE
input shape

### ISSUE THREAD

**Issue by ErlendFax** [NikolasEnt/Road-Semantic-Segmentation#1]
Hi,

I can you chose input shape to be `IMAGE_SHAPE = (160, 576)`. Isn't VGG16 expecting 224x224? Or is this pre-trained model different from normal VGG16?

**Comment by NikolasEnt** [comment]
Hi,
here we use only  conv layers of th VGG, and the image size is not important for the convolution operation.
What is more, the neural network for segmentation is fully convolutional, so, you can train on one image shape, and predict on another.
